<a href="https://colab.research.google.com/github/navyakarna/3D-MODEL-USING-GEN-AI-/blob/main/torch_nn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To even make 1 hidden layer we had to write so much of code , so that's why we have modules in python torch which makesarework easier.


Torch.nn modules

layers - linear , conv2d, MaxPool2d, etc

Activation - sigmoid , tanh , relu

- loss function - mseloss , crosss entropy loss



- torch.autograd module


In [6]:
import torch

NO WE WILL GO TO THE NEXT MODULE WHICH IS OPTIUM , (TORCH.OPTIUM)

-SGD , RMSProp , Adam
THESE ALL ARE INCLUDED IN OPTIUM

In [7]:
a = torch.tensor([[1,1], [1,1]], dtype=torch.float)

Torch.autograd - provides function which do automatic differentiation

In [8]:
b = a + 5
print(b)


tensor([[6., 6.],
        [6., 6.]])


In [11]:
c = b.mean()
print(c)

tensor(6.)


b = a + 5, so c = mean of (a+5)

gradient of c with respect to a , dc/da = dc/db* db/da = 1/4(1+0)*(1+0) = 1/4 = 0.25

BUt we could do the whole process ,

In [12]:
a = torch.tensor([[1,1], [1,1]], dtype=torch.float, requires_grad=True)

In [13]:
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [14]:
b = a+5
c = b.mean()
print(b)
print(c)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)
tensor(6., grad_fn=<MeanBackward0>)


In [18]:
c.backward() #back propagaration

In [17]:
print(a.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
